add error handling for script

diff --git a/todo-project/manifests/backup-configmap.yaml b/todo-project/manifests/backup-configmap.yaml
--- a/todo-project/manifests/backup-configmap.yaml
+++ b/todo-project/manifests/backup-configmap.yaml
@@ -6,9 +6,22 @@ data:
   backup_pg_dump.sh: | 
     #!/bin/bash
     set -e
-    if [ $DATABASE_URL ]
-    then
-      pg_dump -v $DATABASE_URL > ~/backup.sql
-      curl -X PUT --data-binary @~/backup.sql -H "Authorization: Bearer $API_KEY" -H "Content-Type: text/plain " https://storage.googleapis.com/upload/storage/v1/b/gke-dwe/o?uploadType=media&name=postgres-backup"
+    if [ -z "$DATABASE_URL" ]; then
+      echo "$DATABASE_URL not set" 
+      exit 1
+    fi 
+
+
+    pg_dump -v $DATABASE_URL > ~/backup.sql
+    if [ $? -ne 0 ]; then
+      echo "pg_dum failed"
+      exit 1
     fi
+
+    curl -X PUT --data-binary @~/backup.sql -H "Authorization: Bearer $API_KEY" -H "Content-Type: text/plain " https://storage.googleapis.com/upload/storage/v1/b/gke-dwe/o?uploadType=media&name=postgres-backup"
+    fi [ $? -ne 0 ]; then
+      echo "Backup upload failed"
+      exit 1
+    fi
+
 ---
